
services:

    uegmobile_twig_extension.uuid_function:
      class: UEGMobile\UUIDTwigExtensionBundle\Twig\Extension\UUIDExtension
      public: falsess
      tags:
        - { name: twig.extension }
