parameters:
    uegmobile_twig_extension.throw_exceptions: "%kernel.debug%"

services:
#    t4_twig_extension.example:
#        class: T4\Bundle\TwigExtensionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    uegmobile_twig_extension.validator:
      class: T4\Bundle\TwigExtensionBundle\Twig\Extension\ValidatorExtension
      public: false
      arguments:
        - '@validator'
      calls:
        - [setThrowExceptions, ["%t4_twig_extension.throw_exceptions%"]]
      tags:
        - { name: twig.extension }

    t4_twig_extension.ga:
      class: T4\Bundle\TwigExtensionBundle\Twig\Extension\GaExtension
      public: false
      calls:
        - [setThrowExceptions, ["%t4_twig_extension.throw_exceptions%"]]
      tags:
        - { name: twig.extension }

    t4_twig_extension.text:
      class: T4\Bundle\TwigExtensionBundle\Twig\Extension\TextExtension
      public: false
      tags:
        - { name: twig.extension }